"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

It would be more wise to go through all numbers and determine if this number is hexagonal,
pentagonal and triangle. Starting at 40755 is useful.
All hexagonal numbers are triangle, so it's not necessary to test for the latter
"""

def is_penta(entry):
    """
    Checks if the number provided as input is pentagonal
    """
    n = (((24 * entry + 1)**0.5) + 1) / 6
    if n % 1 == 0:
        return True
    else:
        return False

def is_hexa(entry):
    """
    Checks if the number provided as input is hexagonal
    """
    n = (((8 * entry + 1)**0.5) +1) / 4
    if n % 1 == 0:
        return True
    else:
        return False

# Create hexagonal numbers and check if they are pentagonal
for i in range(144, 99999):
    result = i * ( 2 * i - 1)
    if is_penta(result):
        print(i, result)
        break
